### PR TITLE
Copy, paste and template implementation

### PR DESCRIPTION
**Pull request by Sandertv**
This pull request adds working copying, pasting and saving/pasting templates. To merge this pull request, I first need the required translations for it.

Under commands: errors:
+    paste-not-found: "That paste type could not be found."
+    clone-not-found: "That clone type could not be found."
+    name-not-set: "No valid name has been given."
+    template-not-existing: "A template with that name does not exist."

Under commands: succeed:
+    paste: "Pasted the clone successfully."
+    clone: "Area has been cloned and copied successfully."

### CODE REVIEW

**Comment by archie426** [comment]
Can do for Sunday (Away on phone)

**Comment by Sandertv** [comment]
Awesome, no rush!

**Comment by archie426** [comment]
What do you mean by paste not found?

**Comment by Sandertv** [comment]
Basically there's two types of pasting, you can paste a copy, or paste a template.

**Comment by archie426** [comment]
Ah ok

**Comment by HimbeersaftLP** [comment]
> What do you mean by paste not found?

Just translate the English file (en.yml), not the translation names :P

**Comment by Sandertv** [comment]
Weeew, merging time!

**Pull request merged**
