### PR TITLE
Create fr.yml

### PR DESCRIPTION
**Pull request by archie426**
This adds French translations

### CODE REVIEW

**Comment by Sandertv** [comment]
Thanks! :)

**Comment by Sandertv** [comment]
Oops, looks like I failed to explain it to you ._. I were supposed to tell you the English translations (in the en.yml) were the ones to be translated. These default things and stuff are just for access :P Would you mind changing that? It's okay if you don't want to, cause this is awesome too.

**Comment by Sandertv** [comment]
Just the succeed and brushwand messages really, the rest looks good.

**Comment by archie426** [comment]
Oh oops. nooby me

**Comment by Sandertv** [comment]
I think it's good like this, but you'll have to change my edit if it's wrong.

**Comment by archie426** [comment]
Yeah thats fine

**Comment by Sandertv** [comment]
Yeah? Alright :) Thanks a lot!

**Comment by archie426** [comment]
Yeah it is good

**Pull request merged**
